### ISSUE TITLE
Can't get this to install

### ISSUE THREAD

**Issue by Crowley007** [maritz/KoToSoMo#1]
Hello, this seems like a really useful project, but I can't get it to install. It fails with:

Tell the author that this fails on your system:
babel --out-dir dist/ src/

[npm-debug.log.txt](https://github.com/maritz/KoToSoMo/files/547320/npm-debug.log.txt)

**Comment by maritz** [comment]
This is probably my fault: The description says to run `npm install --production` which will not install babel.

Try running `npm install && npm run build && npm run start`

**Comment by Crowley007** [comment]
Thank you for the reply, but I actually found a powershell alternative.

**Comment by maritz** [comment]
I'm curious what that is. Might also help others that possibly land here in the future.

**Comment by Crowley007** [comment]
It's: https://github.com/Blackkatt/ToggleThatEpisode
